name: Pull Request Checks

on:
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - reopened
      - synchronize

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache-dependency-path: 'package-lock.json'
          cache: npm
      - name: Audit
        run: npm audit --audit-level=high
      - name: Comment failed audit in pull request
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'One or more dependencies have failed the security audit step: ' + context.github.server_url + '/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.github.run_id
            })

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node dependencies
        run: npm ci
      - name: Build assets
        run: npm run docs:build
      - name: Comment failed build in pull request
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'One or more build steps have failed: ' + context.github.server_url + '/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.github.run_id
            })
  merge:
    needs:
      - audit
      - build
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
